### ISSUE TITLE
Roadmap for Open Beta

### ISSUE THREAD

**Issue by derme302** [derme302/just-rss#11]
Currently the app is in open beta, this is a non-exhaustive list of items that need to be completed before removing the beta label. 

## Global App

- [ ] Profile Performance and Review
- [ ] #8 

### List

- [ ] Top news/Focus News
- [ ] Natural groups for articles
    - [ ] Trending topics? With only on-device processing
- [ ] Tag support
- [ ] Easy to read, nice font, selectable?
- [ ] Allow for different configuration of time. Date vs How long ago (e.g. 2 hrs ago)

### Feed - Preview

- [ ] Easier next/previous article navigation on source preview

## Sources

- [ ] #3 
- [ ] Combine search and add buttons
- [ ] Implement modal for source config
- [ ] More suggested sources
- [ ] Break feed into a sub-component for the list of entries

## Saved

- [ ] Use feed sub-component for entries
